### PR TITLE
Feature/upgrade dependencies

### PR DESCRIPTION
**Pull request by chefomar**
- fix double quotes typo.
- update dependencies and dev dependencies.
- migrate to latest version of gulp.
- replace browsers options with .browserslistrc file.
- remove unnecessary eslint plugins.
- update eslint config to use eslint recommended.
- fix window.unload is not a function error.
- change unexisting file formspree to formcarry in lint gulp task.
- build new assets.
- add repository & license in package.json to remove npm warning

### CODE REVIEW

**Comment by thomasvaeth** [comment]
Could you run `gulp`? I just pulled everything and I'm getting errors. I upgraded to Gulp 4 on my personal website and it was a huge pain.

**Comment by chefomar** [comment]
I did run `gulp`. Did you upgrade `gulp-cli`? If you don't want to install it globally you can run with `npx gulp build`.

Could you share what errors you are getting? I will try to take a look at them once I get a chance.

**Comment by thomasvaeth** [comment]
```
> barber-jekyll@1.0.0 gulp /Users/thomasvaeth/barber-jekyll
> gulp

/Users/thomasvaeth/barber-jekyll/node_modules/stylelint/node_modules/micromatch/index.js:44
    let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
                                                   ^^^

SyntaxError: Unexpected token ...
```

So I commented out all the stylelint related things in `gulpfile.js`, but then it errors on the spread operator on another function.

**Comment by chefomar** [comment]
What is your node version? can you try with version 8 or higher?

**Comment by thomasvaeth** [comment]
Thank you for your changes. I just merged it in.

**Pull request merged**
